### ISSUE TITLE
USID HDF5 Reader

### ISSUE THREAD

**Issue by ssomnath** [pycroscopy/ScopeReaders#11]
@gduscher has already [put together a function](https://gist.github.com/gduscher/8ac564e567050c7d37ac061b13543c0e) to read USID HDF5 files into ``sidpy.Dataset`` object(s). We need to convert this function / script into a ``Reader`` class for ``ScopeReaders``

**Comment by ssomnath** [comment]
https://github.com/pycroscopy/pyNSID/blob/master/pyNSID/io/usid_reader.py

**Comment by saimani5** [comment]
@ssomnath #18 addresses this.
